Repository dku-capstone/QRust-BE, pull requests merged in 2025-05, with the labels that each got.

#18 feat: QR Code 도메인 설계
  .coderabbit.yaml
  .github/workflows/pr-ci-pipeline.yml
  qrust-api/src/main/java/com/qrust/QrustApiApplication.java
  qrust-api/src/main/resources/application-harvey.yml
  qrust-common/src/main/java/com/qrust/infrastructure/jpa/shared/BaseEntity.java
  qrust-domain/src/main/java/com/qrust/qrcode/domain/entity/QrCode.java
  qrust-domain/src/main/java/com/qrust/qrcode/domain/entity/QrCodeImage.java
  qrust-domain/src/main/java/com/qrust/qrcode/domain/entity/vo/QrCodeData.java
Labels: 🧩 backend, 🔥 feat, 🧹 chore

#23 feat: 보안 QR 코드 생성 및 복호화(추출) 기능 구현
  .coderabbit.yaml
  .github/workflows/pr-ci-pipeline.yml
  .github/workflows/pr-merge-cd-pipeline.yml
  gradle/jackson.gradle
  qrust-api/src/main/resources/application.yml
  qrust-api/src/test/java/com/qrust/qrcode/infrastructure/zxing/QrCodeDecoderImplTest.java
  qrust-api/src/test/java/com/qrust/qrcode/infrastructure/zxing/QrCodeGeneratorImplTest.java
  qrust-api/src/test/resources/generated_qr.png
  qrust-common/src/main/java/com/qrust/config/AesEncryptorConfig.java
  qrust-common/src/main/java/com/qrust/config/ObjectMapperConfig.java
  qrust-common/src/main/java/com/qrust/utils/AesUtil.java
  qrust-domain/build.gradle
  qrust-domain/src/main/java/com/qrust/qrcode/domain/service/QrCodeDecoder.java
  qrust-domain/src/main/java/com/qrust/qrcode/domain/service/QrCodeGenerator.java
  qrust-domain/src/main/java/com/qrust/qrcode/infrastructure/zxing/QrCodeDecoderImpl.java
  qrust-domain/src/main/java/com/qrust/qrcode/infrastructure/zxing/QrCodeGeneratorImpl.java
Labels: 🧩 backend, 🔥 feat, 🧹 chore

#25 chore: api response 응답 구조 통일화
  gradle.properties
  qrust-api/src/main/java/com/qrust/QrustApiApplication.java
  qrust-api/src/main/java/com/qrust/common/dto/ApiResponse.java
  qrust-api/src/main/java/com/qrust/common/dto/ExceptionDto.java
  qrust-api/src/main/java/com/qrust/common/exception/CustomException.java
  qrust-api/src/main/java/com/qrust/common/exception/GlobalExceptionHandler.java
  qrust-api/src/main/java/com/qrust/common/exception/error/ErrorCode.java
  qrust-api/src/main/java/com/qrust/common/interceptor/ApiResponseAdvice.java
  qrust-api/src/main/java/com/qrust/controller/TestController.java
  qrust-api/src/main/resources/application-jhzlo.yml
  qrust-api/src/main/resources/application-prod.yml
  qrust-common/src/main/java/com/qrust/config/SwaggerConfig.java
Labels: 🧩 backend, 🧹 chore

#27 feat: BlackList 기반 url 검사 api 생성
  .github/workflows/pr-ci-pipeline.yml
  build.gradle
  gradle.properties
  gradle/jackson.gradle
  gradle/spring.gradle
  qrust-api/src/main/java/com/qrust/TestController.java
  qrust-api/src/main/java/com/qrust/recognize/controller/GoogleSafeBrowsingController.java
  qrust-api/src/main/java/com/qrust/recognize/swagger/GoogleSafeBrowsingControllerSpec.java
  qrust-api/src/main/resources/application-local.yml
  qrust-api/src/main/resources/application.yml
  qrust-api/src/test/java/com/qrust/external/google/application/GoogleSafeBrowsingServiceTest.java
  qrust-api/src/test/resources/generated_qr.png
  qrust-common/src/main/java/com/qrust/infrastructure/google/config/GoogleSafeBrowsingAuthConfig.java
  qrust-common/src/main/java/com/qrust/infrastructure/google/config/GoogleSafeBrowsingConfig.java
  qrust-domain/src/main/java/com/qrust/common/infrastructure/FeignConfig.java
  qrust-domain/src/main/java/com/qrust/external/google/application/GoogleSafeBrowsingService.java
  qrust-domain/src/main/java/com/qrust/external/google/application/dto/request/GoogleSafeBrowsingRequest.java
  qrust-domain/src/main/java/com/qrust/external/google/application/dto/response/GoogleSafeBrowsingResponse.java
  qrust-domain/src/main/java/com/qrust/external/google/infrastructure/GoogleSafeBrowsingFeignClient.java
Labels: 🧩 backend, 🔥 feat

#28 feat: 큐알 생성 Service 로직 및 Controller 구현
  .github/workflows/pr-ci-pipeline.yml
  .github/workflows/workflow-dispatch-cd-pipeline.yml
  build.gradle
  gradle.properties
  gradle/db.gradle
  gradle/minio.gradle
  gradle/zxing.gradle
  qrust-api/src/main/java/com/qrust/qrcode/controller/QrCodeController.java
  qrust-api/src/main/java/com/qrust/qrcode/controller/swagger/QrCodeControllerSpec.java
  qrust-api/src/main/java/com/qrust/qrcode/dto/QrCodeGenerateRequestDto.java
  qrust-api/src/main/resources/application-harvey.yml
  qrust-api/src/main/resources/application.yml
  qrust-api/src/test/java/com/qrust/qrcode/infrastructure/QrCodeTestTemplate.java
  qrust-api/src/test/java/com/qrust/qrcode/infrastructure/minio/QrCodeMinioUploadImplTest.java
  qrust-api/src/test/java/com/qrust/qrcode/infrastructure/zxing/QrCodeDecoderImplTest.java
  qrust-api/src/test/java/com/qrust/qrcode/infrastructure/zxing/QrCodeGeneratorImplTest.java
  qrust-common/src/main/java/com/qrust/config/MinioConfig.java
  qrust-common/src/main/java/com/qrust/infrastructure/minio/MinioProperties.java
  qrust-domain/build.gradle
  qrust-domain/src/main/java/com/qrust/qrcode/application/QrCodeGeneratorService.java
  qrust-domain/src/main/java/com/qrust/qrcode/domain/entity/QrCode.java
  qrust-domain/src/main/java/com/qrust/qrcode/domain/entity/QrCodeImage.java
  qrust-domain/src/main/java/com/qrust/qrcode/domain/repository/QrCodeImageRepository.java
  qrust-domain/src/main/java/com/qrust/qrcode/domain/repository/QrCodeRepository.java
  qrust-domain/src/main/java/com/qrust/qrcode/domain/service/QrCodeUpload.java
  qrust-domain/src/main/java/com/qrust/qrcode/infrastructure/minio/QrCodeMinioUploadImpl.java
  qrust-domain/src/main/java/com/qrust/qrcode/infrastructure/zxing/QrCodeGeneratorImpl.java
Labels: 🧩 backend, 🔥 feat

#36 feat: QR 코드 조회, 수정, 삭제 API 구현
  build.gradle
  gradle.properties
  gradle/querydsl.gradle
  qrust-api/src/main/java/com/qrust/qrcode/controller/QrCodeController.java
  qrust-api/src/main/java/com/qrust/qrcode/controller/swagger/QrCodeControllerSpec.java
  qrust-domain/src/main/java/com/qrust/common/dto/PageResponse.java
  qrust-domain/src/main/java/com/qrust/common/infrastructure/querydsl/QuerydslConfig.java
  qrust-domain/src/main/java/com/qrust/qrcode/application/QrCodeCommandService.java
  qrust-domain/src/main/java/com/qrust/qrcode/application/QrCodeGeneratorService.java
  qrust-domain/src/main/java/com/qrust/qrcode/application/QrCodeQueryService.java
  qrust-domain/src/main/java/com/qrust/qrcode/domain/entity/QrCode.java
  qrust-domain/src/main/java/com/qrust/qrcode/domain/entity/vo/QrCodeData.java
  qrust-domain/src/main/java/com/qrust/qrcode/domain/entity/vo/QrCodeStatus.java
  qrust-domain/src/main/java/com/qrust/qrcode/domain/entity/vo/QrCodeType.java
  qrust-domain/src/main/java/com/qrust/qrcode/domain/repository/QrCodeQueryRepository.java
  qrust-domain/src/main/java/com/qrust/qrcode/domain/repository/QrCodeRepository.java
  qrust-domain/src/main/java/com/qrust/qrcode/dto/request/QrCodeGenerateRequestDto.java
  qrust-domain/src/main/java/com/qrust/qrcode/dto/request/QrCodeSearchRequestDto.java
  qrust-domain/src/main/java/com/qrust/qrcode/dto/request/QrCodeUpdateRequestDto.java
  qrust-domain/src/main/java/com/qrust/qrcode/dto/response/QrCodeListResponseDto.java
  qrust-domain/src/main/java/com/qrust/qrcode/dto/response/QrCodeResponseDto.java
Labels: 📝 docs, 🧩 backend, 🔥 feat

#39 fix: 엔티티 <-> DTO 간 LocalDateTime <-> LocalDate 변환 오류 수정
  qrust-domain/src/main/java/com/qrust/qrcode/dto/response/QrCodeListResponseDto.java
Labels: 🐞 bug

#40 feat: JWT 기반 회원가입/로그인 구현
  .github/workflows/pr-ci-pipeline.yml
  gradle/db.gradle
  qrust-api/src/main/java/com/qrust/auth/controller/AuthController.java
  qrust-api/src/main/java/com/qrust/auth/resolver/LoginUserArgumentResolver.java
  qrust-api/src/main/java/com/qrust/auth/swagger/AuthControllerSpec.java
  qrust-api/src/main/resources/application.yml
  qrust-common/src/main/java/com/qrust/annotation/user/LoginUser.java
  qrust-common/src/main/java/com/qrust/exception/auth/ErrorMessages.java
  qrust-common/src/main/java/com/qrust/exception/user/ErrorMessages.java
  qrust-common/src/main/java/com/qrust/utils/PasswordHasher.java
  qrust-domain/src/main/java/com/qrust/auth/application/AuthFacade.java
  qrust-domain/src/main/java/com/qrust/auth/dto/LoginRequest.java
  qrust-domain/src/main/java/com/qrust/auth/dto/SignUpRequest.java
  qrust-domain/src/main/java/com/qrust/auth/infrastructure/TokenService.java
  qrust-domain/src/main/java/com/qrust/auth/service/AuthService.java
  qrust-domain/src/main/java/com/qrust/common/config/JwtConfig.java
  qrust-domain/src/main/java/com/qrust/common/config/PasswordConfig.java
  qrust-domain/src/main/java/com/qrust/common/config/SecurityConfig.java
  qrust-domain/src/main/java/com/qrust/common/exception/CustomException.java
  qrust-domain/src/main/java/com/qrust/common/infrastructure/jwt/JwtAuthenticationFilter.java
  qrust-domain/src/main/java/com/qrust/common/infrastructure/jwt/JwtProvider.java
  qrust-domain/src/main/java/com/qrust/common/infrastructure/jwt/JwtValidator.java
  qrust-domain/src/main/java/com/qrust/common/infrastructure/jwt/SecretKeyFactory.java
  qrust-domain/src/main/java/com/qrust/common/infrastructure/redis/RedisConfig.java
  qrust-domain/src/main/java/com/qrust/user/domain/entity/Password.java
  qrust-domain/src/main/java/com/qrust/user/domain/entity/User.java
  qrust-domain/src/main/java/com/qrust/user/domain/entity/vo/Gender.java
  qrust-domain/src/main/java/com/qrust/user/domain/repository/UserRepository.java
  qrust-domain/src/main/java/com/qrust/user/domain/service/PasswordService.java
  qrust-domain/src/main/java/com/qrust/user/domain/service/UserService.java
Labels: 🧩 backend, 🔥 feat

#43 chore: jwt기반 로그인/회원가입 적용
  .github/workflows/pr-ci-pipeline.yml
  gradle/db.gradle
  qrust-api/src/main/java/com/qrust/QrustApiApplication.java
  qrust-api/src/main/java/com/qrust/auth/controller/AuthController.java
  qrust-api/src/main/java/com/qrust/auth/resolver/LoginUserArgumentResolver.java
  qrust-api/src/main/java/com/qrust/auth/swagger/AuthControllerSpec.java
  qrust-api/src/main/resources/application.yml
  qrust-common/src/main/java/com/qrust/annotation/user/LoginUser.java
  qrust-common/src/main/java/com/qrust/exception/auth/ErrorMessages.java
  qrust-common/src/main/java/com/qrust/exception/user/ErrorMessages.java
  qrust-common/src/main/java/com/qrust/utils/PasswordHasher.java
  qrust-domain/src/main/java/com/qrust/auth/application/AuthFacade.java
  qrust-domain/src/main/java/com/qrust/auth/dto/LoginRequest.java
  qrust-domain/src/main/java/com/qrust/auth/dto/SignUpRequest.java
  qrust-domain/src/main/java/com/qrust/auth/infrastructure/TokenService.java
  qrust-domain/src/main/java/com/qrust/auth/service/AuthService.java
  qrust-domain/src/main/java/com/qrust/common/config/JwtConfig.java
  qrust-domain/src/main/java/com/qrust/common/config/PasswordConfig.java
  qrust-domain/src/main/java/com/qrust/common/config/SecurityConfig.java
  qrust-domain/src/main/java/com/qrust/common/exception/CustomException.java
  qrust-domain/src/main/java/com/qrust/common/infrastructure/jwt/JwtAuthenticationFilter.java
  qrust-domain/src/main/java/com/qrust/common/infrastructure/jwt/JwtProvider.java
  qrust-domain/src/main/java/com/qrust/common/infrastructure/jwt/JwtValidator.java
  qrust-domain/src/main/java/com/qrust/common/infrastructure/jwt/SecretKeyFactory.java
  qrust-domain/src/main/java/com/qrust/common/infrastructure/redis/RedisConfig.java
  qrust-domain/src/main/java/com/qrust/user/domain/entity/Password.java
  qrust-domain/src/main/java/com/qrust/user/domain/entity/User.java
  qrust-domain/src/main/java/com/qrust/user/domain/entity/vo/Gender.java
  qrust-domain/src/main/java/com/qrust/user/domain/repository/UserRepository.java
  qrust-domain/src/main/java/com/qrust/user/domain/service/PasswordService.java
  qrust-domain/src/main/java/com/qrust/user/domain/service/UserService.java
Labels: 🧩 backend, 🧹 chore

#46 test: jwt 기반 회원가입/로그인 테스트 코드 작성
  qrust-api/src/main/java/com/qrust/QrustApiApplication.java
  qrust-api/src/test/java/com/qrust/auth/application/AuthFacadeTest.java
  qrust-api/src/test/java/com/qrust/auth/infrastructure/TokenServiceTest.java
  qrust-api/src/test/java/com/qrust/common/infrastructure/jwt/JwtAuthenticationFilterTest.java
  qrust-api/src/test/java/com/qrust/common/infrastructure/jwt/JwtProviderTest.java
  qrust-api/src/test/java/com/qrust/common/infrastructure/jwt/JwtValidatorTest.java
  qrust-common/src/main/java/com/qrust/utils/PasswordHasher.java
  qrust-domain/src/main/java/com/qrust/auth/application/AuthFacade.java
  qrust-domain/src/main/java/com/qrust/common/infrastructure/jwt/JwtAuthenticationFilter.java
Labels: 🧩 backend, 🛡️ test

#53 feat: AI Server API 연동
  .github/workflows/pr-ci-pipeline.yml
  qrust-api/src/main/java/com/qrust/recognize/controller/AiModelController.java
  qrust-api/src/main/java/com/qrust/recognize/swagger/AiModelControllerSpec.java
  qrust-api/src/main/resources/application-local.yml
  qrust-api/src/main/resources/application.yml
  qrust-api/src/test/java/com/qrust/auth/application/AuthFacadeTest.java
  qrust-api/src/test/java/com/qrust/common/infrastructure/jwt/JwtValidatorTest.java
  qrust-domain/src/main/java/com/qrust/common/infrastructure/feign/FeignConfig.java
  qrust-domain/src/main/java/com/qrust/external/ai/application/AiModelUrlVerifyService.java
  qrust-domain/src/main/java/com/qrust/external/ai/application/dto/request/AiModelRequest.java
  qrust-domain/src/main/java/com/qrust/external/ai/application/dto/response/AiModelResponse.java
  qrust-domain/src/main/java/com/qrust/external/ai/infrastructure/AiModelFeignClient.java
Labels: 🧩 backend, 🔥 feat

#56 fix: minio 반환되는 url 주소 수정
  .github/workflows/pr-ci-pipeline.yml
  qrust-api/src/main/resources/application.yml
  qrust-domain/src/main/java/com/qrust/common/infrastructure/s3/MinioProperties.java
  qrust-domain/src/main/java/com/qrust/qrcode/infrastructure/minio/QrCodeMinioUploadImpl.java
Labels: 🐞 bug

#58 QR 코드 도메인 리팩토링
  gradle/spring.gradle
  qrust-api/src/test/java/com/qrust/qrcode/infrastructure/QrCodeTestTemplate.java
  qrust-api/src/test/java/com/qrust/qrcode/infrastructure/minio/QrCodeUploadTest.java
  qrust-common/src/main/java/com/qrust/aop/LoggingAspect.java
  qrust-common/src/main/java/com/qrust/exception/qrcode/ErrorMessages.java
  qrust-common/src/main/java/com/qrust/utils/AesEncryptorUtil.java
  qrust-common/src/main/java/com/qrust/utils/QrCodeEncryptorUtil.java
  qrust-domain/src/main/java/com/qrust/common/config/AesEncryptorConfig.java
  qrust-domain/src/main/java/com/qrust/qrcode/application/QrCodeGeneratorService.java
  qrust-domain/src/main/java/com/qrust/qrcode/application/QrCodeQueryService.java
  qrust-domain/src/main/java/com/qrust/qrcode/domain/service/QrCodeUpload.java
  qrust-domain/src/main/java/com/qrust/qrcode/infrastructure/minio/QrCodeUpload.java
  qrust-domain/src/main/java/com/qrust/qrcode/infrastructure/zxing/QrCodeDecoderImpl.java
  qrust-domain/src/main/java/com/qrust/qrcode/infrastructure/zxing/QrCodeGeneratorImpl.java
Labels: 🪜 refactor

#59 QR 코드 관련 단위 테스트 및 통합 테스트
  .github/workflows/pr-ci-pipeline.yml
  gradle/spring.gradle
  gradle/test.gradle
  qrust-api/src/test/java/com/qrust/qrcode/application/QrCodeCommandServiceTest.java
  qrust-api/src/test/java/com/qrust/qrcode/application/QrCodeGeneratorServiceTest.java
  qrust-api/src/test/java/com/qrust/qrcode/application/QrCodeQueryServiceTest.java
  qrust-api/src/test/java/com/qrust/qrcode/domain/entity/QrCodeTest.java
  qrust-api/src/test/java/com/qrust/qrcode/domain/entity/vo/QrCodeDataTest.java
  qrust-api/src/test/java/com/qrust/qrcode/infrastructure/minio/MinIOIntTest.java
  qrust-api/src/test/java/com/qrust/qrcode/infrastructure/minio/QrCodeUploadTest.java
  qrust-api/src/test/java/com/qrust/qrcode/infrastructure/zxing/QrCodeDecoderImplTest.java
Labels: 🛡️ test

#60 feat: 신고 게시판 엔티티 설계
  qrust-api/src/main/resources/application.yml
  qrust-domain/src/main/java/com/qrust/report/domain/entity/PhishingReport.java
  qrust-domain/src/main/java/com/qrust/report/domain/entity/ReportUrl.java
  qrust-domain/src/main/java/com/qrust/report/domain/entity/vo/ApproveType.java
  qrust-domain/src/main/java/com/qrust/report/domain/entity/vo/ReportType.java
  qrust-domain/src/main/java/com/qrust/report/domain/repository/PhishingReportRepository.java
  qrust-domain/src/main/java/com/qrust/report/domain/repository/ReportUrlRepository.java
Labels: 🧩 backend, 🔥 feat

#62 feat: 신고 게시판 api 생성
  qrust-api/src/main/java/com/qrust/annotation/RoleOnly.java
  qrust-api/src/main/java/com/qrust/annotation/RoleOnlyAspect.java
  qrust-api/src/main/java/com/qrust/auth/controller/AuthController.java
  qrust-api/src/main/java/com/qrust/auth/swagger/AuthControllerSpec.java
  qrust-api/src/main/java/com/qrust/recognize/controller/AiModelController.java
  qrust-api/src/main/java/com/qrust/recognize/controller/GoogleSafeBrowsingController.java
  qrust-api/src/main/java/com/qrust/recognize/swagger/AiModelControllerSpec.java
  qrust-api/src/main/java/com/qrust/recognize/swagger/GoogleSafeBrowsingControllerSpec.java
  qrust-api/src/main/java/com/qrust/report/controller/ReportAdminController.java
  qrust-api/src/main/java/com/qrust/report/controller/ReportController.java
  qrust-api/src/main/java/com/qrust/report/swagger/ReportAdminControllerSpec.java
  qrust-api/src/main/java/com/qrust/report/swagger/ReportControllerSpec.java
  qrust-common/src/main/java/com/qrust/exception/report/ErrorMessages.java
  qrust-common/src/main/java/com/qrust/exception/user/ErrorMessages.java
  qrust-domain/src/main/java/com/qrust/report/application/ReportFacade.java
  qrust-domain/src/main/java/com/qrust/report/domain/entity/PhishingReport.java
  qrust-domain/src/main/java/com/qrust/report/domain/entity/ReportUrl.java
  qrust-domain/src/main/java/com/qrust/report/domain/repository/PhishingReportRepository.java
  qrust-domain/src/main/java/com/qrust/report/domain/repository/ReportUrlRepository.java
  qrust-domain/src/main/java/com/qrust/report/domain/service/PhishingReportService.java
  qrust-domain/src/main/java/com/qrust/report/domain/service/ReportUrlService.java
  qrust-domain/src/main/java/com/qrust/report/dto/PhishingReportDetailResponse.java
  qrust-domain/src/main/java/com/qrust/report/dto/PhishingReportResponse.java
  qrust-domain/src/main/java/com/qrust/report/dto/PhishingReportUpsertRequest.java
  qrust-domain/src/main/java/com/qrust/user/domain/entity/vo/UserRole.java
Labels: 🧩 backend, 🔥 feat

#71 feat: 큐알 목록 페이징 조회 시 현재 상태 필드 반환 추가
  qrust-api/src/test/java/com/qrust/qrcode/application/QrCodeQueryServiceTest.java
  qrust-domain/src/main/java/com/qrust/qrcode/application/QrCodeQueryService.java
  qrust-domain/src/main/java/com/qrust/qrcode/dto/response/QrCodeListResponseDto.java
Labels: 🔥 feat

#74 feat: QR 코드 인식 단일 진입점 api
  qrust-api/src/main/java/com/qrust/recognize/controller/QrRecognizeController.java
  qrust-api/src/main/java/com/qrust/recognize/swagger/QrRecognizeControllerSpec.java
  qrust-domain/src/main/java/com/qrust/recognize/application/RecognizeFacade.java
  qrust-domain/src/main/java/com/qrust/recognize/domain/service/RecognizeService.java
  qrust-domain/src/main/java/com/qrust/recognize/domain/vo/QrCodeVerificationStatus.java
  qrust-domain/src/main/java/com/qrust/recognize/dto/QrCodeVerificationResponse.java
Labels: 🧩 backend, 🔥 feat

#77 infra: Nginx 와 HTTPS 프로토콜 요청 포워딩 추가
  qrust-api/src/main/java/com/qrust/HealthCheckController.java
  qrust-domain/src/main/java/com/qrust/common/config/SecurityConfig.java
Labels: 🏘️ infra, 🧩 backend

#79 refactor: QR 인식 dto 반환 필드 추가, report count
  qrust-api/src/main/java/com/qrust/recognize/controller/QrRecognizeController.java
  qrust-api/src/main/java/com/qrust/user/controller/UserController.java
  qrust-api/src/main/java/com/qrust/user/swagger/UserControllerSpec.java
  qrust-domain/src/main/java/com/qrust/recognize/application/RecognizeFacade.java
  qrust-domain/src/main/java/com/qrust/recognize/dto/QrCodeVerificationResponse.java
  qrust-domain/src/main/java/com/qrust/report/domain/service/ReportUrlService.java
  qrust-domain/src/main/java/com/qrust/user/application/UserFacade.java
  qrust-domain/src/main/java/com/qrust/user/dto/UserResponse.java
Labels: 🧩 backend, 🪜 refactor
